"""conftest.py — evalcraft pytest configuration.

Generated by `evalcraft init --framework {framework}`.

This file is auto-loaded by pytest and wires up evalcraft fixtures and markers
for all tests in the `{tests_dir}/` directory.

Available fixtures (provided by the evalcraft pytest plugin):
    capture_context  — active CaptureContext for the test duration
    mock_llm         — fresh MockLLM instance (records into capture_context)
    mock_tool        — factory that creates MockTool instances
    cassette         — load a Cassette from @pytest.mark.evalcraft_cassette
    replay_engine    — ReplayEngine from @pytest.mark.evalcraft_cassette

Available markers:
    @pytest.mark.evalcraft_cassette("tests/cassettes/foo.json")
    @pytest.mark.evalcraft_capture(name="my_run", save=True)
    @pytest.mark.evalcraft_agent
    @pytest.mark.evalcraft_golden("golden/baseline.golden.json")

CLI flags added to pytest:
    --cassette-dir DIR          Override cassette storage directory
    --evalcraft-record MODE     none | new | all  (default: none)

Usage:
    # Run all tests (replay only — skip if cassette missing)
    pytest {tests_dir}/ -v

    # Record cassettes that don't exist yet
    pytest {tests_dir}/ -v --evalcraft-record=new

    # Always re-record cassettes (overwrite existing)
    pytest {tests_dir}/ -v --evalcraft-record=all
"""

from __future__ import annotations

# The evalcraft pytest plugin is registered as a setuptools entry-point
# (pytest11 = "evalcraft.pytest_plugin.plugin") and loaded automatically
# by pytest.  No explicit imports are required here.
#
# Add any project-specific fixtures or configuration below.
