"""LangGraph agent tests — generated by `evalcraft init`.

Run:
    pytest {tests_dir}/test_agent.py -v

Record a real cassette (requires OPENAI_API_KEY and langgraph installed):
    pytest {tests_dir}/test_agent.py -v --evalcraft-record=new
"""

from __future__ import annotations

import pytest

from evalcraft import CaptureContext, MockLLM
from evalcraft.capture.recorder import get_active_context


# ─── helpers ──────────────────────────────────────────────────────────────────


def run_agent(mock_llm: MockLLM, user_input: str) -> str:
    """Minimal agent loop simulating a LangGraph-style node execution.

    Replace this with your real LangGraph graph when recording cassettes:

        from evalcraft.adapters import LangGraphAdapter
        from evalcraft import CaptureContext

        with CaptureContext(name="my_test") as ctx:
            with LangGraphAdapter(graph):
                result = graph.invoke({"messages": [HumanMessage(user_input)]})
    """
    ctx = get_active_context()
    assert ctx is not None, "run_agent must be called inside a CaptureContext"

    ctx.record_input(user_input)

    # Simulate the agent node making a tool call
    ctx.record_tool_call(
        tool_name="tavily_search",
        args={"query": user_input},
        result={"results": [{"content": "LangGraph is a stateful agent framework."}]},
        duration_ms=200.0,
    )

    # Simulate another node calling the LLM
    response = mock_llm.complete(user_input)
    ctx.record_output(response.content)
    return response.content


# ─── tests ────────────────────────────────────────────────────────────────────


class TestLangGraphAgentCapture:
    """Tests that capture a fresh agent run with a MockLLM."""

    def test_basic_capture_records_spans(self, capture_context, mock_llm):
        """The capture context records LLM calls and tool calls."""
        mock_llm.add_response("*", "LangGraph uses state machines for agent control flow.")

        result = run_agent(mock_llm, "What is LangGraph?")

        assert "LangGraph" in result
        assert capture_context.cassette.llm_call_count >= 1
        assert capture_context.cassette.tool_call_count >= 1

    def test_capture_records_input_and_output(self, capture_context, mock_llm):
        """The cassette stores the agent's input text and output text."""
        mock_llm.add_response("*", "LangGraph enables cyclic agent graphs.")

        run_agent(mock_llm, "Explain LangGraph")

        assert capture_context.cassette.input_text == "Explain LangGraph"
        assert "LangGraph" in capture_context.cassette.output_text

    def test_mock_llm_sequential_responses(self, capture_context, mock_llm):
        """MockLLM.add_sequential_responses returns different answers per call."""
        mock_llm.add_sequential_responses("*", ["Step 1 done", "Step 2 done", "Final answer"])

        r1 = mock_llm.complete("*")
        r2 = mock_llm.complete("*")
        r3 = mock_llm.complete("*")

        assert r1.content == "Step 1 done"
        assert r2.content == "Step 2 done"
        assert r3.content == "Final answer"

    def test_tool_sequence_in_cassette(self, capture_context, mock_llm):
        """The cassette exposes the tool sequence in call order."""
        mock_llm.add_response("*", "Done")
        run_agent(mock_llm, "Search something")

        tool_seq = capture_context.cassette.get_tool_sequence()
        assert "tavily_search" in tool_seq

    def test_cassette_metrics_computed(self, capture_context, mock_llm):
        """After recording, token and cost metrics are non-negative."""
        mock_llm.add_response("*", "Answer", prompt_tokens=60, completion_tokens=30)
        run_agent(mock_llm, "Any query")

        cassette = capture_context.cassette
        cassette.compute_metrics()
        assert cassette.total_tokens >= 0
        assert cassette.total_cost_usd >= 0.0

    def test_mock_llm_call_count(self, capture_context, mock_llm):
        """MockLLM.call_count matches the number of complete() calls."""
        mock_llm.add_response("*", "ok")

        mock_llm.complete("first")
        mock_llm.complete("second")
        mock_llm.complete("third")

        assert mock_llm.call_count == 3

    @pytest.mark.evalcraft_capture(name="langgraph_agent_search")
    def test_capture_with_marker(self, capture_context, mock_llm):
        """The evalcraft_capture marker sets the cassette name."""
        mock_llm.add_response("*", "Found it.")
        run_agent(mock_llm, "Look this up")

        assert capture_context.cassette.name == "langgraph_agent_search"


class TestLangGraphAgentReplay:
    """Replay-based tests — load a cassette and assert its properties."""

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/langgraph_search.json")
    def test_replay_tool_was_called(self, cassette):
        """Replayed cassette must contain a tavily_search tool call."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert "tavily_search" in cassette.get_tool_sequence()

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/langgraph_search.json")
    def test_replay_output_present(self, cassette):
        """Replayed cassette output should be non-empty."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert cassette.output_text is not None
