"""Generic agent tests — generated by `evalcraft init`.

Run:
    pytest {tests_dir}/test_agent.py -v

Save a cassette from a live agent run:
    evalcraft capture my_agent.py --output {tests_dir}/cassettes/my_run.json
"""

from __future__ import annotations

import pytest

from evalcraft import CaptureContext, MockLLM
from evalcraft.capture.recorder import get_active_context


# ─── helpers ──────────────────────────────────────────────────────────────────


def run_agent(mock_llm: MockLLM, user_input: str) -> str:
    """Minimal agent skeleton using evalcraft primitives directly.

    Swap in your real agent code once the tests pass with the mock.
    Record a cassette from a live run with:

        evalcraft capture your_agent_script.py --output tests/cassettes/my_run.json
    """
    ctx = get_active_context()
    assert ctx is not None, "run_agent must be called inside a CaptureContext"

    ctx.record_input(user_input)

    # Simulate a tool call — replace with your real tool
    ctx.record_tool_call(
        tool_name="lookup",
        args={"query": user_input},
        result={"answer": "42"},
        duration_ms=80.0,
    )

    response = mock_llm.complete(user_input)
    ctx.record_output(response.content)
    return response.content


# ─── tests ────────────────────────────────────────────────────────────────────


class TestAgentCapture:
    """Tests that capture a fresh agent run with a MockLLM.

    These run without any API keys or external services — purely local.
    """

    def test_basic_capture_records_spans(self, capture_context, mock_llm):
        """The capture context records at least one LLM call and one tool call."""
        mock_llm.add_response("*", "The answer is 42.")

        result = run_agent(mock_llm, "What is the answer?")

        assert result == "The answer is 42."
        assert capture_context.cassette.llm_call_count >= 1
        assert capture_context.cassette.tool_call_count >= 1

    def test_capture_records_input_and_output(self, capture_context, mock_llm):
        """The cassette stores the agent's input text and output text."""
        mock_llm.add_response("*", "Hello, world!")

        run_agent(mock_llm, "Say hello")

        assert capture_context.cassette.input_text == "Say hello"
        assert capture_context.cassette.output_text == "Hello, world!"

    def test_mock_llm_exact_match(self, mock_llm):
        """MockLLM returns the registered response for an exact prompt match."""
        mock_llm.add_response("ping", "pong")

        assert mock_llm.complete("ping").content == "pong"

    def test_mock_llm_wildcard_fallback(self, mock_llm):
        """MockLLM falls back to the wildcard response for unmatched prompts."""
        mock_llm.add_response("*", "default answer")

        assert mock_llm.complete("anything").content == "default answer"
        assert mock_llm.complete("else").content == "default answer"

    def test_mock_llm_call_count_and_history(self, capture_context, mock_llm):
        """MockLLM tracks every call in call_count and call_history."""
        mock_llm.add_response("*", "ok")

        mock_llm.complete("first")
        mock_llm.complete("second")

        assert mock_llm.call_count == 2
        prompts = [c["prompt"] for c in mock_llm.call_history]
        assert "first" in prompts
        assert "second" in prompts

    def test_cassette_tool_sequence(self, capture_context, mock_llm):
        """The cassette exposes tool calls in the order they were made."""
        mock_llm.add_response("*", "Done")
        run_agent(mock_llm, "What is the answer?")

        tool_seq = capture_context.cassette.get_tool_sequence()
        assert "lookup" in tool_seq

    def test_cassette_fingerprint_computed(self, capture_context, mock_llm):
        """A fingerprint is computed after the CaptureContext exits."""
        mock_llm.add_response("*", "result")
        run_agent(mock_llm, "query")

        # CaptureContext computes fingerprint on __exit__
        assert capture_context.cassette.fingerprint is not None

    def test_cassette_metrics_non_negative(self, capture_context, mock_llm):
        """Token count and cost are always >= 0 after metrics computation."""
        mock_llm.add_response("*", "Answer", prompt_tokens=50, completion_tokens=20)
        run_agent(mock_llm, "Question")

        cassette = capture_context.cassette
        cassette.compute_metrics()
        assert cassette.total_tokens >= 0
        assert cassette.total_cost_usd >= 0.0

    @pytest.mark.evalcraft_capture(name="generic_agent_run")
    def test_capture_with_marker(self, capture_context, mock_llm):
        """The evalcraft_capture marker names the cassette."""
        mock_llm.add_response("*", "Named capture result.")
        run_agent(mock_llm, "Named test")

        assert capture_context.cassette.name == "generic_agent_run"


class TestAgentReplay:
    """Replay-based tests — load a cassette and assert its properties.

    Cassettes can be created by running a live agent:
        evalcraft capture my_agent.py --output {tests_dir}/cassettes/my_run.json
    """

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/my_run.json")
    def test_replay_tool_called(self, cassette):
        """Replayed cassette must contain a lookup tool call."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert "lookup" in cassette.get_tool_sequence()

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/my_run.json")
    def test_replay_has_output(self, cassette):
        """Replayed cassette should have a non-empty output text."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert cassette.output_text is not None
        assert len(cassette.output_text) > 0
