"""OpenAI agent tests — generated by `evalcraft init`.

Run:
    pytest {tests_dir}/test_agent.py -v

Record a real cassette (requires OPENAI_API_KEY):
    pytest {tests_dir}/test_agent.py -v --evalcraft-record=new
"""

from __future__ import annotations

import pytest

from evalcraft import CaptureContext, MockLLM
from evalcraft.capture.recorder import get_active_context


# ─── helpers ──────────────────────────────────────────────────────────────────


def run_agent(mock_llm: MockLLM, user_input: str) -> str:
    """Minimal agent loop using a MockLLM.

    Replace this with your real OpenAI-backed agent when recording cassettes.
    """
    ctx = get_active_context()
    assert ctx is not None, "run_agent must be called inside a CaptureContext"

    # Record user input
    ctx.record_input(user_input)

    # Simulate a tool call
    ctx.record_tool_call(
        tool_name="get_weather",
        args={"city": "New York"},
        result={"temp": 72, "condition": "sunny"},
        duration_ms=50.0,
    )

    # Simulate the LLM final response
    response = mock_llm.complete(user_input)

    # Record the agent output
    ctx.record_output(response.content)
    return response.content


# ─── tests ────────────────────────────────────────────────────────────────────


class TestOpenAIAgentCapture:
    """Tests that capture a fresh agent run with a MockLLM."""

    def test_basic_capture_records_spans(self, capture_context, mock_llm):
        """The capture context records LLM calls and tool calls."""
        mock_llm.add_response("*", "It is 72°F and sunny in New York.")

        result = run_agent(mock_llm, "What is the weather in New York?")

        assert result == "It is 72°F and sunny in New York."
        # Captured at least one LLM span and one tool span
        assert capture_context.cassette.llm_call_count >= 1
        assert capture_context.cassette.tool_call_count >= 1

    def test_capture_records_input_and_output(self, capture_context, mock_llm):
        """The cassette stores the agent's input text and output text."""
        mock_llm.add_response("*", "It is 72°F and sunny.")

        run_agent(mock_llm, "Weather in NY?")

        assert capture_context.cassette.input_text == "Weather in NY?"
        assert capture_context.cassette.output_text == "It is 72°F and sunny."

    def test_mock_llm_returns_expected_content(self, mock_llm):
        """MockLLM resolves exact-match and wildcard responses correctly."""
        mock_llm.add_response("What is 2+2?", "4")
        mock_llm.add_response("*", "I don't know")

        assert mock_llm.complete("What is 2+2?").content == "4"
        assert mock_llm.complete("Something else").content == "I don't know"

    def test_mock_llm_records_call_history(self, capture_context, mock_llm):
        """Every mock call is tracked in MockLLM.call_history."""
        mock_llm.add_response("*", "ok")
        mock_llm.complete("Hello")
        mock_llm.complete("World")

        assert mock_llm.call_count == 2
        prompts = [c["prompt"] for c in mock_llm.call_history]
        assert "Hello" in prompts
        assert "World" in prompts

    def test_cassette_metrics_computed(self, capture_context, mock_llm):
        """After recording, token and cost metrics are non-negative."""
        mock_llm.add_response("*", "Done", prompt_tokens=50, completion_tokens=25)
        run_agent(mock_llm, "Run the agent")

        cassette = capture_context.cassette
        cassette.compute_metrics()
        assert cassette.total_tokens >= 0
        assert cassette.total_cost_usd >= 0.0

    def test_tool_sequence_in_cassette(self, capture_context, mock_llm):
        """The cassette exposes the recorded tool sequence."""
        mock_llm.add_response("*", "Done")
        run_agent(mock_llm, "What's the weather?")

        tool_seq = capture_context.cassette.get_tool_sequence()
        assert "get_weather" in tool_seq

    @pytest.mark.evalcraft_capture(name="openai_agent_weather")
    def test_capture_with_marker(self, capture_context, mock_llm):
        """The evalcraft_capture marker sets the cassette name."""
        mock_llm.add_response("*", "Sunny skies.")
        run_agent(mock_llm, "Weather?")

        assert capture_context.cassette.name == "openai_agent_weather"


class TestOpenAIAgentReplay:
    """Replay-based tests — load a cassette and assert its properties.

    These tests are skipped when the cassette does not exist yet.
    Run with --evalcraft-record=new to create it from a live run.
    """

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/openai_weather.json")
    def test_replay_tool_was_called(self, cassette):
        """Replayed cassette must contain a get_weather tool call."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert "get_weather" in cassette.get_tool_sequence()

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/openai_weather.json")
    def test_replay_output_mentions_weather(self, cassette):
        """Replayed cassette output should contain weather information."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert cassette.output_text is not None
        assert len(cassette.output_text) > 0
