"""CrewAI agent tests — generated by `evalcraft init`.

Run:
    pytest {tests_dir}/test_agent.py -v

Record a real cassette (requires crewai installed and an LLM API key):
    pytest {tests_dir}/test_agent.py -v --evalcraft-record=new
"""

from __future__ import annotations

import pytest

from evalcraft import CaptureContext, MockLLM
from evalcraft.capture.recorder import get_active_context


# ─── helpers ──────────────────────────────────────────────────────────────────


def run_crew(mock_llm: MockLLM, topic: str) -> str:
    """Minimal crew simulation using MockLLM.

    Replace this with your real CrewAI crew when recording cassettes:

        from evalcraft.adapters import CrewAIAdapter
        from evalcraft import CaptureContext

        with CaptureContext(name="crew_run") as ctx:
            with CrewAIAdapter(crew):
                result = crew.kickoff(inputs={"topic": topic})
    """
    ctx = get_active_context()
    assert ctx is not None, "run_crew must be called inside a CaptureContext"

    ctx.record_input(topic)

    # Researcher agent tool calls
    ctx.record_tool_call(
        tool_name="web_search",
        args={"query": f"research {topic}"},
        result={"results": [{"title": f"About {topic}", "content": "Detailed findings..."}]},
        duration_ms=300.0,
    )

    # Writer agent tool calls
    ctx.record_tool_call(
        tool_name="file_write",
        args={"filename": "report.md", "content": f"Report on {topic}"},
        result={"success": True},
        duration_ms=50.0,
    )

    response = mock_llm.complete(f"Summarize research about {topic}")
    ctx.record_output(response.content)
    return response.content


# ─── tests ────────────────────────────────────────────────────────────────────


class TestCrewAIAgentCapture:
    """Tests that capture a fresh crew run with a MockLLM."""

    def test_basic_capture_records_spans(self, capture_context, mock_llm):
        """The capture context records LLM calls and tool calls from all agents."""
        mock_llm.add_response("*", "AI safety research is a growing field.")

        result = run_crew(mock_llm, "AI safety")

        assert result == "AI safety research is a growing field."
        assert capture_context.cassette.llm_call_count >= 1
        assert capture_context.cassette.tool_call_count >= 2

    def test_capture_records_input_and_output(self, capture_context, mock_llm):
        """The cassette stores the crew's input topic and final output."""
        mock_llm.add_response("*", "A comprehensive report on climate change.")

        run_crew(mock_llm, "climate change")

        assert "climate change" in capture_context.cassette.input_text
        assert capture_context.cassette.output_text is not None

    def test_multiple_tool_types_in_sequence(self, capture_context, mock_llm):
        """Crew runs typically call multiple distinct tools in sequence."""
        mock_llm.add_response("*", "Report generated.")

        run_crew(mock_llm, "quantum computing")

        tool_seq = capture_context.cassette.get_tool_sequence()
        assert "web_search" in tool_seq
        assert "file_write" in tool_seq

    def test_tool_call_count_matches_agent_calls(self, capture_context, mock_llm):
        """Tool call count matches what the crew made during execution."""
        mock_llm.add_response("*", "Done")
        run_crew(mock_llm, "some topic")

        assert capture_context.cassette.tool_call_count == 2

    def test_cassette_metrics_computed(self, capture_context, mock_llm):
        """After recording, token and cost metrics are non-negative."""
        mock_llm.add_response("*", "Summary", prompt_tokens=100, completion_tokens=50)
        run_crew(mock_llm, "test")

        cassette = capture_context.cassette
        cassette.compute_metrics()
        assert cassette.total_tokens >= 0
        assert cassette.total_cost_usd >= 0.0

    @pytest.mark.evalcraft_capture(name="crewai_research_run")
    def test_capture_with_marker(self, capture_context, mock_llm):
        """The evalcraft_capture marker sets the cassette name."""
        mock_llm.add_response("*", "Research complete.")
        run_crew(mock_llm, "evalcraft")

        assert capture_context.cassette.name == "crewai_research_run"


class TestCrewAIAgentReplay:
    """Replay-based tests — load a cassette and assert its properties."""

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/crewai_research.json")
    def test_replay_both_tools_were_called(self, cassette):
        """Replayed cassette must contain web_search and file_write tool calls."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        seq = cassette.get_tool_sequence()
        assert "web_search" in seq
        assert "file_write" in seq

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/crewai_research.json")
    def test_replay_output_present(self, cassette):
        """Replayed cassette output should be non-empty."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert cassette.output_text is not None
        assert len(cassette.output_text) > 0
