"""Anthropic agent tests — generated by `evalcraft init`.

Run:
    pytest {tests_dir}/test_agent.py -v

Record a real cassette (requires ANTHROPIC_API_KEY):
    pytest {tests_dir}/test_agent.py -v --evalcraft-record=new
"""

from __future__ import annotations

import pytest

from evalcraft import CaptureContext, MockLLM
from evalcraft.capture.recorder import get_active_context


# ─── helpers ──────────────────────────────────────────────────────────────────


def run_agent(mock_llm: MockLLM, user_input: str) -> str:
    """Minimal agent loop using a MockLLM.

    Replace this with your real Anthropic-backed agent when recording cassettes.
    The real version would use AnthropicAdapter inside the CaptureContext:

        from evalcraft.adapters import AnthropicAdapter
        import anthropic

        client = anthropic.Anthropic()

        with CaptureContext(name="my_test") as ctx:
            with AnthropicAdapter():
                response = client.messages.create(
                    model="claude-3-5-sonnet-20241022",
                    max_tokens=1024,
                    messages=[{"role": "user", "content": user_input}],
                )
    """
    ctx = get_active_context()
    assert ctx is not None, "run_agent must be called inside a CaptureContext"

    ctx.record_input(user_input)

    ctx.record_tool_call(
        tool_name="web_search",
        args={"query": user_input},
        result={"results": [{"title": "Anthropic", "url": "https://anthropic.com"}]},
        duration_ms=120.0,
    )

    response = mock_llm.complete(user_input)
    ctx.record_output(response.content)
    return response.content


# ─── tests ────────────────────────────────────────────────────────────────────


class TestAnthropicAgentCapture:
    """Tests that capture a fresh agent run with a MockLLM."""

    def test_basic_capture_records_spans(self, capture_context, mock_llm):
        """The capture context records LLM calls and tool calls."""
        mock_llm.add_response("*", "Anthropic was founded in 2021.")

        result = run_agent(mock_llm, "Who founded Anthropic?")

        assert "Anthropic" in result
        assert capture_context.cassette.llm_call_count >= 1
        assert capture_context.cassette.tool_call_count >= 1

    def test_capture_records_input_and_output(self, capture_context, mock_llm):
        """The cassette stores the agent's input text and output text."""
        mock_llm.add_response("*", "Claude is made by Anthropic.")

        run_agent(mock_llm, "Who made Claude?")

        assert capture_context.cassette.input_text == "Who made Claude?"
        assert "Claude" in capture_context.cassette.output_text

    def test_mock_llm_returns_expected_content(self, mock_llm):
        """MockLLM resolves exact-match and wildcard responses correctly."""
        mock_llm.add_response("What model are you?", "I am Claude.")
        mock_llm.add_response("*", "I can help with that.")

        assert mock_llm.complete("What model are you?").content == "I am Claude."
        assert mock_llm.complete("Something else").content == "I can help with that."

    def test_mock_llm_records_call_history(self, capture_context, mock_llm):
        """Every mock call is tracked in MockLLM.call_history."""
        mock_llm.add_response("*", "ok")
        mock_llm.complete("Hello")
        mock_llm.complete("Goodbye")

        assert mock_llm.call_count == 2
        prompts = [c["prompt"] for c in mock_llm.call_history]
        assert "Hello" in prompts
        assert "Goodbye" in prompts

    def test_cassette_metrics_computed(self, capture_context, mock_llm):
        """After recording, token and cost metrics are non-negative."""
        mock_llm.add_response("*", "Done", prompt_tokens=80, completion_tokens=40)
        run_agent(mock_llm, "Run the agent")

        cassette = capture_context.cassette
        cassette.compute_metrics()
        assert cassette.total_tokens >= 0
        assert cassette.total_cost_usd >= 0.0

    def test_tool_sequence_in_cassette(self, capture_context, mock_llm):
        """The cassette exposes the recorded tool sequence."""
        mock_llm.add_response("*", "Done")
        run_agent(mock_llm, "Search something")

        tool_seq = capture_context.cassette.get_tool_sequence()
        assert "web_search" in tool_seq

    @pytest.mark.evalcraft_capture(name="anthropic_agent_search")
    def test_capture_with_marker(self, capture_context, mock_llm):
        """The evalcraft_capture marker sets the cassette name."""
        mock_llm.add_response("*", "Found it.")
        run_agent(mock_llm, "Search?")

        assert capture_context.cassette.name == "anthropic_agent_search"


class TestAnthropicAgentReplay:
    """Replay-based tests — load a cassette and assert its properties.

    These tests are skipped when the cassette does not exist yet.
    Run with --evalcraft-record=new to create it from a live run.
    """

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/anthropic_search.json")
    def test_replay_tool_was_called(self, cassette):
        """Replayed cassette must contain a web_search tool call."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert "web_search" in cassette.get_tool_sequence()

    @pytest.mark.evalcraft_cassette("{tests_dir}/cassettes/anthropic_search.json")
    def test_replay_output_present(self, cassette):
        """Replayed cassette output should be non-empty."""
        if cassette is None:
            pytest.skip("Cassette not recorded yet.")
        assert cassette.output_text is not None
        assert len(cassette.output_text) > 0
